/*
============================================================
Exploratory Data Analysis: Magntitude Exploration
============================================================

Purpose:
	This script defines the ways to explore the magnitudes in the tables as a part of EDA.

	1. Check for the aggregations.
	2. Explore the different magnitudes.
	3. formulae is [Dimension by Measure]

*/

-- Select total customers with respect to their countries
SELECT 
COUNT(customer_id),
country 
FROM Gold.dim_customers
GROUP BY country;

-- Select total sales by country 
SELECT 
SUM(fc.sales) AS total_sales,
dc.country
FROM Gold.fact_sales AS fc
LEFT JOIN Gold.dim_customers AS dc
ON fc.customer_key = dc.customer_key
GROUP BY country;

--  Select total products by category
SELECT 
COUNT(product_id) AS total_products,
category
FROM Gold.dim_products
GROUP BY category;

-- Select Average cost in each category
SELECT 
category,
AVG(cost) AS avg_cost_category
FROM Gold.dim_products
GROUP BY category;

-- Select total revenue for each category
SELECT 
category,
SUM(cost) AS total_revenue
FROM Gold.dim_products
GROUP BY category;

-- Select total revenue of category accessories
SELECT 
SUM(cost)
FROM Gold.dim_products
WHERE category = 'Accessories';

-- Select Total revenue generated by each customer
SELECT 
customer_key,
SUM(sales) AS total_revenue
FROM Gold.fact_sales
GROUP BY customer_key;